version: "3"
services:
  nlp:
    build: .
    environment:
      NLP_ENV: dev
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  postgres:
    image: postgres:9.6.1
    ports:
      - "5444:5432"
